// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrl1kCCF3JXo8GlVi-54E40rDgVOsxDY',
    appId: '1:487601441257:web:f378db281c54b957b9e378',
    messagingSenderId: '487601441257',
    projectId: 'sign-in-52308',
    authDomain: 'sign-in-52308.firebaseapp.com',
    storageBucket: 'sign-in-52308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxJtZBxs8mHyVXIucB21Isx6U5bKznhM',
    appId: '1:487601441257:android:15ec634bf423de53b9e378',
    messagingSenderId: '487601441257',
    projectId: 'sign-in-52308',
    storageBucket: 'sign-in-52308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjAmERzgpFfYU1WKLduFxOG1UtAX9rrQ',
    appId: '1:487601441257:ios:6f23e8b1be972985b9e378',
    messagingSenderId: '487601441257',
    projectId: 'sign-in-52308',
    storageBucket: 'sign-in-52308.appspot.com',
    iosBundleId: 'com.example.duplicate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYjAmERzgpFfYU1WKLduFxOG1UtAX9rrQ',
    appId: '1:487601441257:ios:73dd5b7b11652806b9e378',
    messagingSenderId: '487601441257',
    projectId: 'sign-in-52308',
    storageBucket: 'sign-in-52308.appspot.com',
    iosBundleId: 'com.example.duplicate.RunnerTests',
  );
}
